import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeWrapper } from "@/components/themeWrapper"; // Import the client-side wrapper
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" href="/vercel.svg" sizes="any" />
      </head>
      <body className={`${inter.className}`}>
        <ThemeWrapper>
          <div className="relative w-full flex items-center justify-center">
            <Navbar />
          </div>
          {children}
          <Footer />
        </ThemeWrapper>
      </body>
    </html>
  );
}
